<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
  
  	<groupId>6b803037-b7da-4678-8714-01519ec4530a</groupId>
	<artifactId>generic_error_handler_mule</artifactId>
	<version>1.0.0</version>
	<packaging>mule-application</packaging>
	<name>generic_error_handler_mule</name>
   <parent>
      <groupId>6b803037-b7da-4678-8714-01519ec4530a</groupId>
      <artifactId>parent-pom</artifactId>
      <version>1.0.0</version>
   </parent>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>${maven-clean-plugin-version}</version>
			</plugin>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<version>${mule-maven-plugin-version}</version>
				<extensions>true</extensions>
				<configuration>
					<classifier>mule-plugin</classifier>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-tracing-module</artifactId>
			<version>${mule-tracing-module-version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>6b803037-b7da-4678-8714-01519ec4530a</groupId>
			<artifactId>json-logger</artifactId>
			<version>${json-logger-version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
           <artifactId>mule-apikit-module</artifactId>
			<version>${mule-apikit-module-version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
	</dependencies>
	<repositories>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
			<layout>default</layout>
		</repository>
		<repository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<url>https://repository.mulesoft.org/releases/</url>
			<layout>default</layout>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<layout>default</layout>
			<url>https://repository.mulesoft.org/releases/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
</project>
